spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3307/mydb
#    username: root
#    password: example0000

  jpa:
    hibernate:
      ddl-auto: create-drop

  mail:
    host: localhost
    username: 반려독
    password:
    port: 1025

jwt:
  secret:
    key: testkeytestkeyeraskdfjlkasdjflksjdflkjsdlkfjlskdjfmustbechanged

email:
  auth:
    subject: "반려멍 이메일 인증코드입니다."